// =============================================================================
// ConMart — Buyer Orders Page
// =============================================================================
// Lists all proforma invoices generated by the current buyer with
// bilingual English & Amharic presentation.
// =============================================================================

import { redirect } from "next/navigation";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { fetchBuyerOrders } from "@/lib/data/catalog";
import { OrdersView } from "./orders-view";

export default async function BuyerOrdersPage() {
  const user = await getAuthenticatedUser();
  if (!user) {
    redirect("/login?redirect=/buyer/orders");
  }

  const orders = await fetchBuyerOrders(user.id);

  return <OrdersView orders={orders} />;
}
